-- ---------------------------------------------------------------------------
-- AutoQA — Supabase schema
--
-- Run this once in a new Supabase project (SQL Editor → New query → Run).
-- Creates the two tables the CLI writes to and the dashboard reads from,
-- plus the indexes that keep the Command Center's "latest-N" queries fast.
--
-- Safe to run multiple times: every DDL statement uses IF NOT EXISTS.
-- ---------------------------------------------------------------------------

-- Test matrices generated by `autoqa generate-matrix --push-supabase`.
CREATE TABLE IF NOT EXISTS test_matrices (
  id           bigserial    PRIMARY KEY,
  source_url   text         NOT NULL,
  page_title   text,
  captured_at  timestamptz,
  generated_at timestamptz  NOT NULL DEFAULT now(),
  total_cases  integer      NOT NULL DEFAULT 0,
  dom_map      jsonb,
  cases        jsonb        NOT NULL
);

-- Bug reports generated by `autoqa run --push-supabase`.
CREATE TABLE IF NOT EXISTS bug_reports (
  id            bigserial   PRIMARY KEY,
  test_id       text,
  test_title    text        NOT NULL,
  describe_path text,
  source_spec   text,
  status        text        NOT NULL,
  expected      text,
  actual        text,
  error_message text,
  error_stack   text,
  duration_ms   integer,
  run_at        timestamptz NOT NULL DEFAULT now()
);

-- Indexes: the Command Center always sorts by "most recent first".
CREATE INDEX IF NOT EXISTS idx_test_matrices_generated_at
  ON test_matrices (generated_at DESC);

CREATE INDEX IF NOT EXISTS idx_bug_reports_run_at
  ON bug_reports (run_at DESC);
