/**
 * Command Center — the dashboard's landing page.
 *
 * Server Component. Fetches the most recent test matrices and bug
 * reports from Supabase in parallel, with tight column selection so
 * payloads stay small even as the tables grow. Renders four stat
 * cards plus two data panels (matrices + failures).
 *
 * If Supabase env vars aren't configured yet, the page renders a
 * "setup required" state instead of crashing — handy for the very
 * first Render deploy before secrets are wired up.
 */

import { formatDistanceToNow, format } from 'date-fns';
import {
  ClipboardList,
  Bug,
  AlertTriangle,
  Clock3,
  ExternalLink,
  CheckCircle2,
  Settings2,
  Activity,
} from 'lucide-react';

import { getSupabaseClient, isSupabaseConfigured } from '@/lib/supabase';
import type {
  TestMatrixRow,
  BugReportRow,
  DashboardStats,
} from '@/lib/types';

// Always render fresh per request — QA data is live and cheap to re-query.
export const dynamic = 'force-dynamic';

/* ------------------------------------------------------------------ */
/*  Data loading                                                       */
/* ------------------------------------------------------------------ */

interface CommandCenterData {
  stats: DashboardStats;
  recentMatrices: TestMatrixRow[];
  recentBugReports: BugReportRow[];
  error?: string;
}

async function loadCommandCenterData(): Promise<CommandCenterData> {
  const empty: CommandCenterData = {
    stats: {
      totalMatrices: 0,
      totalCases: 0,
      totalBugReports: 0,
      lastRunAt: null,
    },
    recentMatrices: [],
    recentBugReports: [],
  };

  const supabase = getSupabaseClient();
  if (!supabase) return empty;

  // Parallelized lean queries — only the columns we render, with head
  // counts to get totals without streaming every row.
  const [matricesRes, bugReportsRes, matrixCountRes, bugCountRes] = await Promise.all([
    supabase
      .from('test_matrices')
      .select('id, source_url, page_title, captured_at, generated_at, total_cases')
      .order('generated_at', { ascending: false })
      .limit(5),
    supabase
      .from('bug_reports')
      .select(
        'id, test_id, test_title, describe_path, source_spec, status, expected, actual, duration_ms, run_at',
      )
      .order('run_at', { ascending: false })
      .limit(10),
    supabase
      .from('test_matrices')
      .select('total_cases', { count: 'exact', head: false })
      .limit(1000),
    supabase
      .from('bug_reports')
      .select('id', { count: 'exact', head: true }),
  ]);

  const firstError =
    matricesRes.error ||
    bugReportsRes.error ||
    matrixCountRes.error ||
    bugCountRes.error;
  if (firstError) {
    return { ...empty, error: firstError.message };
  }

  const recentMatrices = (matricesRes.data ?? []) as TestMatrixRow[];
  const recentBugReports = (bugReportsRes.data ?? []) as BugReportRow[];

  const totalCases =
    (matrixCountRes.data ?? []).reduce(
      (sum: number, row: { total_cases: number | null }) =>
        sum + (row.total_cases ?? 0),
      0,
    ) ?? 0;

  const lastRunAt = recentBugReports[0]?.run_at ?? recentMatrices[0]?.generated_at ?? null;

  return {
    stats: {
      totalMatrices: matrixCountRes.count ?? recentMatrices.length,
      totalCases,
      totalBugReports: bugCountRes.count ?? recentBugReports.length,
      lastRunAt,
    },
    recentMatrices,
    recentBugReports,
  };
}

/* ------------------------------------------------------------------ */
/*  Page                                                               */
/* ------------------------------------------------------------------ */

export default async function CommandCenterPage() {
  const configured = isSupabaseConfigured();
  const data = configured
    ? await loadCommandCenterData()
    : ({
        stats: {
          totalMatrices: 0,
          totalCases: 0,
          totalBugReports: 0,
          lastRunAt: null,
        },
        recentMatrices: [],
        recentBugReports: [],
      } as CommandCenterData);

  return (
    <div className="mx-auto w-full max-w-7xl px-6 py-10 sm:px-10">
      <PageHeader />

      {!configured && <SetupRequiredBanner />}
      {configured && data.error && <ErrorBanner message={data.error} />}

      <section className="mt-8 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <StatCard
          label="Test Matrices"
          value={data.stats.totalMatrices.toLocaleString()}
          caption="Generated by the CLI"
          icon={ClipboardList}
          accent="emerald"
        />
        <StatCard
          label="Total Cases"
          value={data.stats.totalCases.toLocaleString()}
          caption="Across every matrix"
          icon={Activity}
          accent="cyan"
        />
        <StatCard
          label="Bug Reports"
          value={data.stats.totalBugReports.toLocaleString()}
          caption="Failing Playwright runs"
          icon={Bug}
          accent="rose"
        />
        <StatCard
          label="Last Activity"
          value={
            data.stats.lastRunAt
              ? formatDistanceToNow(new Date(data.stats.lastRunAt), {
                  addSuffix: true,
                })
              : '—'
          }
          caption={
            data.stats.lastRunAt
              ? format(new Date(data.stats.lastRunAt), 'PPpp')
              : 'No CLI runs recorded yet'
          }
          icon={Clock3}
          accent="amber"
        />
      </section>

      <section className="mt-10 grid grid-cols-1 gap-6 xl:grid-cols-5">
        <Panel
          className="xl:col-span-3"
          title="Recent Test Matrices"
          subtitle="The five most recent matrices pushed by the CLI."
          icon={ClipboardList}
        >
          {data.recentMatrices.length === 0 ? (
            <EmptyState
              icon={ClipboardList}
              title="No test matrices yet"
              body="Run `autoqa generate-matrix --push-supabase` to send your first matrix here."
            />
          ) : (
            <MatricesTable rows={data.recentMatrices} />
          )}
        </Panel>

        <Panel
          className="xl:col-span-2"
          title="Recent Bug Reports"
          subtitle="The ten most recent Playwright failures."
          icon={Bug}
        >
          {data.recentBugReports.length === 0 ? (
            <EmptyState
              icon={CheckCircle2}
              title="No bug reports"
              body="No failures on record. Run `autoqa run --push-supabase` after a test run to populate this panel."
            />
          ) : (
            <BugReportsList rows={data.recentBugReports} />
          )}
        </Panel>
      </section>
    </div>
  );
}

/* ------------------------------------------------------------------ */
/*  Sub-components                                                     */
/* ------------------------------------------------------------------ */

function PageHeader() {
  return (
    <header className="flex flex-col gap-2 border-b border-slate-800 pb-6 sm:flex-row sm:items-end sm:justify-between">
      <div>
        <p className="text-xs font-semibold uppercase tracking-[0.2em] text-emerald-400">
          Command Center
        </p>
        <h1 className="mt-1 text-3xl font-semibold tracking-tight text-slate-50">
          QA activity overview
        </h1>
        <p className="mt-2 max-w-2xl text-sm text-slate-400">
          Live view of every AI-authored test matrix and Playwright bug report
          pushed by the AutoQA CLI.
        </p>
      </div>
      <div className="flex items-center gap-2 rounded-full border border-slate-800 bg-slate-900/50 px-4 py-1.5 text-xs font-medium text-slate-400">
        <span className="h-2 w-2 rounded-full bg-emerald-400" />
        Live · reads from Supabase
      </div>
    </header>
  );
}

interface StatCardProps {
  label: string;
  value: string;
  caption: string;
  icon: React.ComponentType<React.SVGProps<SVGSVGElement>>;
  accent: 'emerald' | 'cyan' | 'rose' | 'amber';
}

function StatCard({ label, value, caption, icon: Icon, accent }: StatCardProps) {
  const accents: Record<StatCardProps['accent'], string> = {
    emerald: 'bg-emerald-500/10 text-emerald-300 ring-emerald-500/20',
    cyan: 'bg-cyan-500/10 text-cyan-300 ring-cyan-500/20',
    rose: 'bg-rose-500/10 text-rose-300 ring-rose-500/20',
    amber: 'bg-amber-500/10 text-amber-300 ring-amber-500/20',
  };
  return (
    <div className="rounded-xl border border-slate-800 bg-slate-900/40 p-5 transition-colors hover:border-slate-700">
      <div className="flex items-center justify-between">
        <span className="text-xs font-medium uppercase tracking-wider text-slate-500">
          {label}
        </span>
        <span
          className={`inline-flex h-8 w-8 items-center justify-center rounded-lg ring-1 ${accents[accent]}`}
        >
          <Icon className="h-4 w-4" />
        </span>
      </div>
      <p className="mt-4 text-2xl font-semibold tracking-tight text-slate-50">
        {value}
      </p>
      <p className="mt-1 text-xs text-slate-500">{caption}</p>
    </div>
  );
}

interface PanelProps {
  title: string;
  subtitle: string;
  icon: React.ComponentType<React.SVGProps<SVGSVGElement>>;
  className?: string;
  children: React.ReactNode;
}

function Panel({ title, subtitle, icon: Icon, className, children }: PanelProps) {
  return (
    <section
      className={`overflow-hidden rounded-xl border border-slate-800 bg-slate-900/40 ${className ?? ''}`}
    >
      <header className="flex items-start justify-between border-b border-slate-800 px-5 py-4">
        <div>
          <h2 className="flex items-center gap-2 text-sm font-semibold text-slate-100">
            <Icon className="h-4 w-4 text-slate-400" />
            {title}
          </h2>
          <p className="mt-0.5 text-xs text-slate-500">{subtitle}</p>
        </div>
      </header>
      <div className="p-5">{children}</div>
    </section>
  );
}

function MatricesTable({ rows }: { rows: TestMatrixRow[] }) {
  return (
    <div className="overflow-x-auto">
      <table className="w-full text-left text-sm">
        <thead>
          <tr className="border-b border-slate-800 text-xs uppercase tracking-wider text-slate-500">
            <th className="pb-3 pr-4 font-medium">Page</th>
            <th className="pb-3 pr-4 font-medium">Cases</th>
            <th className="pb-3 pr-4 font-medium">Generated</th>
            <th className="pb-3 font-medium" />
          </tr>
        </thead>
        <tbody>
          {rows.map((row) => {
            const host = safeHost(row.source_url);
            return (
              <tr
                key={row.id}
                className="border-b border-slate-900 last:border-b-0 hover:bg-slate-900/60"
              >
                <td className="py-3 pr-4">
                  <div className="font-medium text-slate-100">
                    {row.page_title || host || 'Untitled page'}
                  </div>
                  <div className="truncate text-xs text-slate-500">
                    {row.source_url}
                  </div>
                </td>
                <td className="py-3 pr-4">
                  <span className="inline-flex items-center rounded-md bg-emerald-500/10 px-2 py-1 text-xs font-semibold text-emerald-300 ring-1 ring-inset ring-emerald-500/20">
                    {row.total_cases}
                  </span>
                </td>
                <td className="py-3 pr-4 text-xs text-slate-400">
                  <div>
                    {formatDistanceToNow(new Date(row.generated_at), {
                      addSuffix: true,
                    })}
                  </div>
                  <div className="text-slate-600">
                    {format(new Date(row.generated_at), 'PP p')}
                  </div>
                </td>
                <td className="py-3 text-right">
                  <a
                    href={row.source_url}
                    target="_blank"
                    rel="noreferrer"
                    className="inline-flex items-center gap-1 text-xs font-medium text-slate-400 transition-colors hover:text-emerald-300"
                  >
                    Source
                    <ExternalLink className="h-3 w-3" />
                  </a>
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>
    </div>
  );
}

function BugReportsList({ rows }: { rows: BugReportRow[] }) {
  return (
    <ol className="space-y-3">
      {rows.map((row) => (
        <li
          key={row.id}
          className="rounded-lg border border-slate-800 bg-slate-950/40 p-3 transition-colors hover:border-rose-500/40"
        >
          <div className="flex items-start justify-between gap-2">
            <div className="min-w-0">
              <div className="flex items-center gap-2">
                <StatusBadge status={row.status} />
                {row.test_id && (
                  <span className="font-mono text-[10px] font-semibold text-slate-500">
                    {row.test_id}
                  </span>
                )}
              </div>
              <p className="mt-1 truncate text-sm font-medium text-slate-100">
                {row.test_title}
              </p>
              {row.describe_path && (
                <p className="mt-0.5 truncate text-xs text-slate-500">
                  {row.describe_path}
                </p>
              )}
            </div>
            <span className="shrink-0 text-[10px] text-slate-500">
              {formatDistanceToNow(new Date(row.run_at), { addSuffix: true })}
            </span>
          </div>
          {row.actual && (
            <p className="mt-2 line-clamp-2 text-xs text-slate-400">
              <span className="font-semibold text-rose-300">Actual:</span>{' '}
              {row.actual}
            </p>
          )}
        </li>
      ))}
    </ol>
  );
}

function StatusBadge({ status }: { status: string }) {
  const map: Record<string, string> = {
    failed: 'bg-rose-500/10 text-rose-300 ring-rose-500/20',
    timedOut: 'bg-amber-500/10 text-amber-300 ring-amber-500/20',
    interrupted: 'bg-slate-500/10 text-slate-300 ring-slate-500/20',
  };
  const classes = map[status] ?? 'bg-slate-500/10 text-slate-300 ring-slate-500/20';
  return (
    <span
      className={`inline-flex items-center rounded-full px-2 py-0.5 text-[10px] font-semibold uppercase ring-1 ring-inset ${classes}`}
    >
      {status}
    </span>
  );
}

function EmptyState({
  icon: Icon,
  title,
  body,
}: {
  icon: React.ComponentType<React.SVGProps<SVGSVGElement>>;
  title: string;
  body: string;
}) {
  return (
    <div className="flex flex-col items-center justify-center gap-2 rounded-lg border border-dashed border-slate-800 bg-slate-950/30 px-4 py-10 text-center">
      <Icon className="h-6 w-6 text-slate-600" />
      <p className="text-sm font-medium text-slate-200">{title}</p>
      <p className="max-w-sm text-xs text-slate-500">{body}</p>
    </div>
  );
}

function SetupRequiredBanner() {
  return (
    <div className="mt-6 flex items-start gap-3 rounded-lg border border-amber-500/30 bg-amber-500/5 p-4">
      <Settings2 className="mt-0.5 h-5 w-5 shrink-0 text-amber-400" />
      <div className="text-sm text-amber-100">
        <p className="font-semibold">Supabase credentials not configured.</p>
        <p className="mt-1 text-amber-200/80">
          Set{' '}
          <code className="rounded bg-amber-500/10 px-1 py-0.5 font-mono text-xs">
            NEXT_PUBLIC_SUPABASE_URL
          </code>{' '}
          and{' '}
          <code className="rounded bg-amber-500/10 px-1 py-0.5 font-mono text-xs">
            NEXT_PUBLIC_SUPABASE_ANON_KEY
          </code>{' '}
          in your deployment environment (see{' '}
          <code className="rounded bg-amber-500/10 px-1 py-0.5 font-mono text-xs">
            .env.local.example
          </code>
          ) and redeploy.
        </p>
      </div>
    </div>
  );
}

function ErrorBanner({ message }: { message: string }) {
  return (
    <div className="mt-6 flex items-start gap-3 rounded-lg border border-rose-500/30 bg-rose-500/5 p-4">
      <AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-rose-400" />
      <div className="text-sm text-rose-100">
        <p className="font-semibold">Supabase query failed.</p>
        <p className="mt-1 font-mono text-xs text-rose-200/80">{message}</p>
      </div>
    </div>
  );
}

function safeHost(url: string): string | null {
  try {
    return new URL(url).hostname;
  } catch {
    return null;
  }
}
